#!/bin/bash

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ] && [ $ALACRITTY_LOG ]; then
    exec tmux new-session && exit;
fi
